### ISSUE TITLE
ServiceProvider

### ISSUE THREAD

**Issue by imanghafoori1** [DivineOmega/laravel-password-exposed-validation-rule#11]
You may have a service provider to register the new nice validation rule in it.

```php
\Validator::extend(...
```

**Comment by DivineOmega** [comment]
Good idea. :+1: 

Feel free to open a PR. If not, I'll probably tackle this myself at some point over the next few days.

**Comment by imanghafoori1** [comment]
I am not sure about contribution since I am busy for a few days... any way it is a small change.
