### ISSUE TITLE
unserialize(): Error at offset 0 of 17729 bytes

### ISSUE THREAD

**Issue by SreejithEzhakkad** [DivineOmega/laravel-password-exposed-validation-rule#12]
Hi, I am getting the following error for some passwords, like "Siva@2507" 

![error](https://user-images.githubusercontent.com/19388006/49721985-98424880-fc89-11e8-93ce-f400f6054a8b.png)

**Comment by DivineOmega** [comment]
@SreejithEzhakkad Thanks for the report. This was an issue with an update to the underlying caching library. This should now have been resolved.

Run a `composer update` and it should work as expected.

**Comment by SreejithEzhakkad** [comment]
Done, It is working now!. Thanks.
