### ISSUE TITLE
Having issue on Windows.

### ISSUE THREAD

**Issue by jason-guru** [DivineOmega/laravel-password-exposed-validation-rule#13]
Hi I am on windows and it's throwing an exception 
`Your PHP installation does not support `sys_getloadavg` (Windows?). Please set `unixLoadUpperThreshold` to `-1` in your DOFileCache config`,
but the unixLoadUpperThreshold is already set to -1 (default config) and I am still getting the above message. Any help would be great...

Thanks

**Comment by jason-guru** [comment]
### Implementation
`<?php

namespace App\Http\Requests\Backend\Auth\User;

use App\Rules\Auth\ChangePassword;
use App\Rules\Auth\UnusedPassword;
use Illuminate\Foundation\Http\FormRequest;
use DivineOmega\LaravelPasswordExposedValidationRule\PasswordExposed;

/**
 * Class UpdateUserPasswordRequest.
 */
class UpdateUserPasswordRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return $this->user()->isAdmin();
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'password'     => [
                'required',
                'confirmed',
                new ChangePassword(),
                new PasswordExposed(),
                new UnusedPassword((int) $this->segment(4)),
            ],
        ];
    }
}`
### Default Config
![do_setting](https://user-images.githubusercontent.com/34002768/49811873-27cf2080-fd8a-11e8-8dd1-e06fa2823776.PNG)

### Error snippet
![divineomega_issue](https://user-images.githubusercontent.com/34002768/49811911-3c131d80-fd8a-11e8-8137-c8e5876364af.PNG)

**Comment by DivineOmega** [comment]
Thanks.

I believe you might be on an old version of `DO-File-Cache`. Could you provide me with the output of `composer outdated`?

**Comment by jason-guru** [comment]
I think it's outdated, here is the composer outdated snippet

![composer_outdated](https://user-images.githubusercontent.com/34002768/49814786-5c45db00-fd90-11e8-84ee-d771a2720163.PNG)

**Comment by jason-guru** [comment]
Woohoo!! Thanks for your time and fast response. Everything's working great now.

**Comment by DivineOmega** [comment]
My pleasure. I think this specific issue was fixed in [DO-File-Cache v2.0.3](https://github.com/DivineOmega/DO-File-Cache/releases/tag/v2.0.3).

**Comment by DivineOmega** [comment]
Given the type of password rules you're implementing, you might want to take a look at the [Laravel NIST Password Rules](https://github.com/langleyfoxall/laravel-nist-password-rules) package, which uses include this one and includes several other password rules.

**Comment by jason-guru** [comment]
The package looks awesome and thanks again for your valuable suggestion.
