### ISSUE TITLE
PHP 8 Support?

### ISSUE THREAD

**Issue by oriceon** [DivineOmega/laravel-password-exposed-validation-rule#22]

**Comment by emielmolenaar** [comment]
This would be nice.

**Comment by Jamesking56** [comment]
@DivineOmega Any chance of this being scheduled in?

**Comment by brunogaspar** [comment]
I've "set up" forks of the necessary packages.

If you are stuck and until the package get's a release with PHP8, if you wan't, you can use my forks.

To use you need to perform a few adjustments in your `composer.json` file.

Add the following repositories:

```json
"repositories": [
    {
        "type": "vcs",
        "url": "git@github.com:brunogaspar/psr-18-guzzle-adapter"
    },
    {
        "type": "vcs",
        "url": "git@github.com:brunogaspar/password_exposed"
    },
    {
        "type": "vcs",
        "url": "git@github.com:brunogaspar/laravel-password-exposed-validation-rule"
    }
],
```

Then update the dependency to use the `php8` branch:

```json
"divineomega/laravel-password-exposed-validation-rule": "dev-php8"
```

Then ensure your minimum stability is is set to `dev`

```json
"minimum-stability": "dev",
"prefer-stable": true
```

Hope it helps :)

**Comment by brunogaspar** [comment]
Thanks for v2.4.0 release @DivineOmega 

This can be closed now i believe :)
